---
- hosts: puppet
  tasks:
  - name: 1. Installation de centos release scl
    package: name=centos-release-scl state=present
  - name: 2. Recup√©ration du RPM dePuppet
    get_url:
      url: https://yum.puppetlabs.com/puppetlabs-release-pc1-el-9.noarch.rpm
      dest: /tmp/puppetlabs-release-pc1-el-9.noarch.rpm
  - name: 3. Retire le check des cl√© gpg dePuppet
    package: name=/tmp/puppetlabs-release-pc1-el-9.noarch.rpm disable_gpg_check=no
  - name: 4. Installation du packet Puppet
    package: name=puppetserver state=installed
  - name: 5. Rechargement des daemons  
    shell: systemctl daemon-reload
  - name: 6. D√©marrage des servicesPuppet
    service: name={{item}} state=started enabled=yes
  - name: 7. Ajout de la r√gle de Firewall
    action: command firewall-cmd --permanent --add-port=8140/tcp && firewall-cmd --permanent --add-port=8081/tcp
